# Generated by Django 5.0.4 on 2024-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_lecturer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_status',
            name='lecturer_comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_status',
            name='student_comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='additional_status',
            field=models.CharField(blank=True, default='Не просмотрено', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='status',
            field=models.CharField(blank=True, default='Не сдано', max_length=50, null=True),
        ),
    ]
