# Generated by Django 5.0.4 on 2024-04-12 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_laboratory_group_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
