# Generated by Django 5.0.4 on 2024-04-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lecturer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='group',
        ),
    ]
