# Generated by Django 5.0.4 on 2024-04-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_creasted_at_educationalgroup_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name': 'Лабораторные работы', 'verbose_name_plural': 'Лабораторные работы'},
        ),
        migrations.AlterModelOptions(
            name='laboratory_status',
            options={'verbose_name': 'Статусы лабораторных работ по студентам', 'verbose_name_plural': 'Статусы лабораторных работ по студентам'},
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='educational',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lecturer', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='additional_status',
            field=models.CharField(blank=True, choices=[('Просмотрено', 'Просмотрено'), ('Не просмотрено', 'Не просмотрено')], default='Не просмотрено', max_length=50, null=True, verbose_name='Статус просмотра'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.laboratory', verbose_name='Лабораторная работа'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='lecturer_comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='status',
            field=models.CharField(blank=True, choices=[('Сдано', 'Сдано'), ('Не сдано', 'Не сдано')], default='Не сдано', max_length=50, null=True, verbose_name='Статус сдачи'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='student_comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Комментарий студента'),
        ),
        migrations.AlterField(
            model_name='laboratory_status',
            name='student_status',
            field=models.CharField(blank=True, choices=[('Сгенерировал QR', 'Сгенерировал QR'), ('Не сгенерировал QR', 'Не сгенерировал QR')], default='Не сгенерировал QR', max_length=50, null=True, verbose_name='Статус студента'),
        ),
    ]
