# Generated by Django 5.0.4 on 2024-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студенты', 'verbose_name_plural': 'Студенты'},
        ),
    ]
